#spring.application.name=Chatbot
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.h2.console.enabled=true
# ?? Server ??????????????????????????????????????????????
server.port=8080



openai.api.key=${OPENAI_API_KEY}
# ?? Groq API ????????????????????????????????????????????
groq.api.key=${GROQ_API_KEY}

# ?? H2 In-Memory Database ??????????????????????????????? this wil only save db temporary !
#spring.datasource.url=jdbc:h2:mem:chatbotdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driver-class-name=org.h2.Driver

#h2 memory in local disk
spring.datasource.url=jdbc:h2:file:./data/chatbotdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver


spring.datasource.username=sa
spring.datasource.password=

# ?? JPA / Hibernate ?????????????????????????????????????
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create-drop


# CHANGED: create-drop ? update (keeps data on restart)
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# ?? H2 Web Console (useful for debugging) ???????????????
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ?? Static resources ????????????????????????????????????
spring.web.resources.static-locations=classpath:/static/